telegram:
  token: ""

database:
  host: "localhost"
  port: 5432
  user: "postgres"
  password: ""
  dbname: "postgres"
  sslmode: "disable"
  use_in_memory: false

classifier:
  min_confidence: 0.7
  max_tags: 5

openai:
  api_key: ""
  model: "gpt-3.5-turbo"
  max_tokens: 150
  temperature: 0.7 