telegram:
  token: ${TELEGRAM_TOKEN}

database:
  host: ${PGHOST}
  port: ${PGPORT}
  user: ${PGUSER}
  password: ${PGPASSWORD}
  dbname: ${PGDATABASE}
  sslmode: disable
  use_in_memory: false

classifier:
  min_confidence: 0.7
  max_tags: 5

openai:
  api_key: ${OPENAI_API_KEY}
  model: "gpt-3.5-turbo"
  max_tokens: 150
  temperature: 0.7 