# fly.toml app configuration file generated for memo-bot on 2025-01-08T19:11:57+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'memo-bot'
primary_region = 'ams'

[build]
  dockerfile = 'Dockerfile'

[env]
  MAX_TAGS = '5'
  MIN_CONFIDENCE = '0.7'
  USE_IN_MEMORY_DB = 'false'

[deploy]
  strategy = "bluegreen"
  release_command = "sleep 10" # Give the database time to be ready

[[services]]
  protocol = "tcp"
  internal_port = 8080
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1

  [[services.ports]]
    port = 80
    handlers = ["http"]

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]

  [services.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20

  [[services.tcp_checks]]
    interval = "15s"
    timeout = "2s"
    grace_period = "30s"

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 256

[mounts]
  source = "postgres_data"
  destination = "/data"
