# fly.toml app configuration file generated for memo-bot-purple-flower-5901 on 2025-01-08T18:53:44+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'memo-bot-purple-flower-5901'
primary_region = 'ams'

[build]
  dockerfile = 'Dockerfile'

[env]
  MAX_TAGS = '5'
  MIN_CONFIDENCE = '0.7'
  USE_IN_MEMORY_DB = 'false'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 256
